name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure assets and scss are correctly available
      - name: Move index.html to docs
        run: |
          mkdir -p docs
          mv index.html docs/

      # Setup Ruby environment and Jekyll build
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build site
        run: |
          jekyll build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  # Latest stable version
        with:
          branch: main
          folder: docs
